name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.11.4
        with:
          heroku_app_name: YOUR_HEROKU_APP_NAME
          heroku_email: YOUR_HEROKU_EMAIL
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
